Pokemon/Models/Animal.cs
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;
using Newtonsoft.Json.Linq;
using System.Reflection.Emit;

namespace Pokemon.Models
{
    public class Animal
    {
        public int MyProperty { get; set; }
        public int Vida { get; set; }
        public int DainoMagico { get; set; }
        public int DainoFisico { get; set; }
        public string Nombre { get; set; }
        public int velocidad { get; set; }

        public Animal(int idf, int vidaf, int DainoMagicof, int DainoFisicof, String nomf, int velocidadf) {
            MyProperty = idf;
            Vida = vidaf;
            DainoMagico = DainoMagicof;
            DainoFisico = DainoFisicof;
            Nombre = nomf;
            velocidad = velocidadf;
        }
        public Animal()
        {
        }

    }
}

Pokemon/Models/ErrorViewModel.cs
namespace Pokemon.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Pokemon/Controllers/AnimalController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.DotNet.Scaffolding.Shared.Messaging;
using Newtonsoft.Json.Linq;
using Pokemon.Models;
using System.Configuration;

namespace Pokemon.Controllers
{
    public class AnimalController : Controller
    {
        private static List<Animal> animales = new List<Animal>();
        public static List<Animal> AnimalesProp
        {
            get{
            return animales;    
            }  
        }

        public IActionResult Index()
        {
            //aqui mostramos todos los animes           
            return View(animales);
        }
        public ActionResult Create()
        {
            if (animales.Count <= 6) {
                /*sacarid*/
                int idf;
                if (animales.Count > 0)
                {
                    Animal animalConMayorMyProperty = animales.OrderByDescending(a => a.MyProperty).FirstOrDefault();
                    idf = animalConMayorMyProperty.MyProperty + 1;
                }
                else
                {
                    idf = 1;
                }
                // Aquí va tu lógica para la acción "Create"
                Random rand = new Random();
                int min = 10; // valor mínimo
                int max = 20; // valor máximo
                int numeroAleatorio = rand.Next(min, max);
                int vidaf = numeroAleatorio;
                int myproperty = animales.Count + 1;
                min = 1; // valor mínimo
                max = 10; // valor máximo
                numeroAleatorio = rand.Next(min, max);
                int DainoMagicof = numeroAleatorio;
                numeroAleatorio = rand.Next(min, max);
                int DainoFisicof = numeroAleatorio;
                numeroAleatorio = rand.Next(min, max);
                int velocidadf = numeroAleatorio;
                /*nombre*/
                List<Animal> pokemons = new List<Animal>();
                string[] nombresPokemon = new string[] {  "Caterpie","Beedrill", "Pidgey","Arbok","Sandslash","Vulpix", "Ninetales", "Jigglypuff", "Parasect","Dugtrio" };
                numeroAleatorio = rand.Next(1, nombresPokemon.Length);
                String Nombref = nombresPokemon[numeroAleatorio];
                Animal obk = new Animal(idf,vidaf, DainoMagicof, DainoFisicof, Nombref, velocidadf);
                animales.Add(obk);
                Console.WriteLine("aaa");
            }
            
            return RedirectToAction("Index");
        }
        public ActionResult Delete(int MyProperty)
        {
            Console.WriteLine(MyProperty);
            for (int i = 0; i < animales.Count(); i++)
            {
                if (animales[i].MyProperty == MyProperty)
                {
                    animales.RemoveAt(i);
                    i = 50;
                }
            }
            return RedirectToAction("Index");
        }
        public ActionResult Pelear()
        {
            ViewBag["HayPokemon"] = animales;
            return View(animales);
        }
    }
}

Pokemon/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Pokemon.Models;
using System.Diagnostics;

namespace Pokemon.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            ViewData["AnimalesProp"]=AnimalController.AnimalesProp.Count;

            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Pokemon/Views/Animal/Index.cshtml
@model IEnumerable<Pokemon.Models.Animal>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

@* <p>
    <a asp-action="Create">Create New</a>
</p> *@
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.MyProperty)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <th>
                @Html.ActionLink("Crear", "Create", new { /* id=item.PrimaryKey */ })
            </th>
        </tr>
@foreach (var item in Model) {
            <tr>
                <th>nombre</th>
                <th>Daño fisico</th>
                <th>daño amgico</th>
                <th>vida</th>
                <th>valocidad</th>
                <th>ID</th>
            <td></tr><tr><td>
                @Html.DisplayFor(modelItem => item.Nombre)
                </td><td>
                @Html.DisplayFor(modelItem => item.DainoFisico)
                </td>
                <td>
                @Html.DisplayFor(modelItem => item.DainoMagico)
                </td>
                <td>
                @Html.DisplayFor(modelItem => item.Vida)
                </td>
                <td>
                @Html.DisplayFor(modelItem => item.velocidad)
                </td>
                <td>
                @Html.DisplayFor(modelItem => item.MyProperty)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Delete", "Delete", new {item.MyProperty }) |         
            </td>
        </tr>
}
    </tbody>
</table>

Pokemon/Views/Animal/Pelear.cshtml
@model IEnumerable<Pokemon.Models.Animal>

@{
    ViewData["Title"] = "Pelear";
}

<h1>Pelear</h1>
@if (Model.Any())
{
    
}
@* <table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.MyProperty)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Vida)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DainoMagico)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DainoFisico)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nombre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.velocidad)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.MyProperty)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Vida)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DainoMagico)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DainoFisico)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nombre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.velocidad)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
            </td>
        </tr>
}
    </tbody>
</table>
 *@

Pokemon/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page".ToUpper();
    String pedo = "aa";
    ViewData["Title"] = pedo;
    ViewData["caramelito"]= "ajo";

}
<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <h1>
        @* @ViewData["caramelito"].ToString() *@
        <a asp-area="" asp-controller="Animal" asp-action="Index">Crear equipo</a>
    </h1>

    <h1>
        @* @ViewData["caramelito"].ToString() *@
        @if ((int)ViewData["AnimalesProp"] > 0)
        {
            <a asp-area="" asp-controller="Animal" asp-action="Pelear">Pelear</a>
        }
        
    </h1>
</div>

Pokemon/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Pokemon</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Pokemon.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Pokemon</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Pokemon - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>